name: CI

on:
  push:
    branches:
      - main
    paths:
    - 'posts/**'
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: Publish posts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.3

      - name: List all modified files
        id: list
        run: |
          declare -A folders
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do          
            echo "$file was modified"
            folders[$(dirname "$file")]="."            
          done
          post_folders=()
          for x in "${!folders[@]}"; do
            expected="$x/metadata.json"
            if [ -f "$expected" ]; then
              post_folders+=($x)
              echo "Post folder $x"            
            fi            
          done      
          echo ::set-output name=folders::${post_folders[@]}

      - name: Publish folders
        env:
          DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
          DEVTO_USER: ${{ secrets.DEVTO_USER }}
        run: |
          for folder in ${{ steps.list.outputs.folders }}; do
            echo "ðŸš€ publish.sh $folder"
            bash publisher.sh $folder            
          done

      - name: Update README.md
        run: |
          bash update_readme.sh
          python --version

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update files
